export {
  NecConditioningError,
  NecError,
  NecGeometryError,
  NecInputError,
  NecPortError,
  NecRuntimeError,
  NecSolverError,
  NecStateError,
} from "./errors.js";

export { abiVersion, engineVersion, packageVersion } from "./versions.js";
export { rotationalOrder } from "./symmetry.js";
export { analyzeArraySymmetry, createExplicitArrayBuildPlan } from "./array-symmetry.js";
export {
  applyArrayBuildPlan,
  createNecArraySolver,
  gatherComplexMatrix,
  gatherComplexVector,
  gatherEmbeddedBasis,
  rephaseFarField,
  scatterComplexVector,
} from "./array-solver.js";
export type { AppliedArrayBuildPlan } from "./array-solver.js";

export type { NecErrorCode, NecErrorOptions } from "./errors.js";

export { createNecWorkerModel } from "./worker-client.js";

export type {
  AngleSweep,
  ArrayBuildPlan,
  ArrayElementId,
  ArrayElementMapping,
  ArraySolverDiagnostics,
  CartesianSignsTransform,
  CartesianPointM,
  CanonicalArrayElement,
  CompleteGeometryOptions,
  ComplexMatrix,
  ComplexVector,
  ConductivityLoad,
  CreateArraySolverOptions,
  CreateNecModelOptions,
  CurrentModeKind,
  CreateNecWorkerModelOptions,
  DistributedParallelRlcLoad,
  DistributedSeriesRlcLoad,
  EmbeddedFarFieldResult,
  EmbeddedFieldNormalization,
  ElementWirePattern,
  FarFieldRequest,
  FarFieldDiagnostics,
  FarFieldResult,
  FiniteGround,
  FreeSpaceGround,
  FullArrayDescription,
  GeometryCompletionResult,
  GeometrySymmetry,
  GroundConnection,
  GroundModel,
  ImpedanceLoad,
  ImpedanceResult,
  IsolatedElementCharacterization,
  LoadDefinition,
  NecArraySolver,
  NecCurrentDistribution,
  NecModelState,
  NecSegmentEnd,
  NecSegmentIdentity,
  NecWorkerModel,
  NecWorkerOperation,
  NecWorkerProgressEvent,
  NecWorkerProgressListener,
  ParallelRlcLoad,
  PerfectGround,
  PortDefinition,
  PortSolution,
  PositionCanonicalization,
  PositionedArrayElement,
  PreparedQuadratureImages,
  PreparedQuadratureRequest,
  PreparedTransferHandle,
  PrepareOptions,
  ReflectionPlane,
  ReflectionSymmetry,
  RelativeLoadDefinition,
  RelativePortDefinition,
  RelativeSegmentSelection,
  RelativeWireDefinition,
  RotationalOrder,
  RotationalSymmetry,
  RotateZTransform,
  SegmentSelection,
  SeriesRlcLoad,
  SymmetryCopy,
  SymmetryCopyTransform,
  SymmetryExpansion,
  SymmetryFailureClassification,
  SymmetryFailureReason,
  SymmetrizationReason,
  SymmetrizationReasonCode,
  SymmetrizerDiagnostics,
  SymmetrizerOptions,
  SymmetryCandidateDiagnostics,
  WireDefinition,
} from "./types.js";
